.TH crunchyfrog 1 2009\-03\-16
.SH NAME
crunchyfrog \- SQL client (not\-only) for GNOME
.SH SYNOPSIS
.B crunchyfrog
[OPTIONS] [FILE1, ...]
.SH DESCRIPTION
CrunchyFrog is a database navigator and SQL client.

It's mainly written for GNOME but it should run in other environments too.

Supported databases
===================

 * PostgreSQL (requires psycopg2)
 * MySQL (requires MySQLdb)
 * SQLite3 (requires python\-sqlite3)
 * Oracle (requires cx_Oracle)
 * MS\-SQL Server (requires pymssql)
 * LDAP (requires python\-ldap)

It is written in Python (PyGTK) and can be extended using plugins.

Check out the homepage for the most recent version and details.
.SH OPTIONS
.TP
.B \-\-version
show program's version number and exit
.TP
.B \-h, \-\-help
show this help message and exit
.TP
.B \-c CONFIG, \-\-config=CONFIG
configuration file

.TP
LOGGING OPTIONS
.TP
.B \-q, \-\-quiet
Print errors only.
.TP
.B \-v, \-\-verbose
Print info level logs (default).
.TP
.B \-\-noisy
Print all logs.
.SH AUTHORS
.B crunchyfrog
was written by Andi Albrecht <albrecht.andi@gmail.com>.
.SH DISTRIBUTION
The latest version of crunchyfrog may be downloaded from
.UR http://crunchyfrog.googlecode.com
.UE
