.\" Copyright (C) 2008 Andi Albrecht <albrecht.andi@gmail.com>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this; if not write to the Free Software Foundation, Inc.
.\" 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
.TH crunchyfrog 1 "2008\-02\-18"
.SH NAME
crunchyfrog \- Simple GNOME database tool
.SH SYNOPSIS
.B crunchyfrog
.RI [ option... ] " " [ file name ]
.SH DESCRIPTION
.B crunchyfrog
is a simple database schema browser and query tool for the GNOME desktop.
.SH OPTIONS
.TP
.B -c, --config
Configuration file to use (default: ~/.config/crunchyfrog/config)
.TP
.B -v,--version
Print the version and exit
.TP
.B -d, --debug
Output debug messages on the console output. Disabled by default.

.SH AUTHORS
.B crunchyfrog
was written by the Andi Albrecht <albrecht.andi@gmail.com>
.SH DISTRIBUTION
The latest version of crunchyfrog may be downloaded from
.UR http://cf.andialbrecht.de
<http://cf.andialbrecht.de/>
.UE
